name: CI

on: [pull_request]

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v2

      - name: Read Node version from .nvmrc
        run: echo ::set-output name=NVMRC::$(cat .nvmrc)
        id: nvm

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '${{ steps.nvm.outputs.NVMRC }}'

      - uses: actions/cache@v2
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-node-v${{ steps.nvm.outputs.NVMRC }}-modules-${{ hashFiles('yarn.lock') }}

      - name: Install packages
        run: yarn install --frozen-lockfile

      - name: Run CI script
        run: yarn ci
